apiVersion: v1
kind: Service
metadata:
  name: lottery-service
  labels:
    app: lottery-app
spec:
  selector:
    app: lottery-app
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
